# 2 pts Create a notebook, import Pandas, and import the data as a dataframe.

==> In next two cells I have Imported all the required package and also using pandas CSV function I have imported the dataset as well.

In [29]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier


In [30]:
data = pd.read_csv('C:\\Users\\Mohan Kumar\\Downloads\\data\\adult.csv')
data

age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13      32            Private  205019     Assoc-acdm             12   
14      40            Private  121772      Assoc-voc             11   
15      34            Private  245487        7th-8th              4   
16      25   Self-emp-not-inc  176756        HS-grad              9   
17      32            Private  186824        HS-grad              9   
18      38            Private   28887           11th              7   
19      43   Self-emp-not-inc  292175        Masters             14   
20      40            Private  193524      Doctorate             16   
21      54            Private  302146        HS-grad              9   
22      35        Federal-gov   76845            9th              5   
23      43            Private  117037           11th              7   
24      59            Private  109015        HS-grad              9   
25      56          Local-gov  216851      Bachelors             13   
26      19            Private  168294        HS-grad              9   
27      54                  ?  180211   Some-college             10   
28      39            Private  367260        HS-grad              9   
29      49            Private  193366        HS-grad              9   
...    ...                ...     ...            ...            ...   
32531   30                  ?   33811      Bachelors             13   
32532   34            Private  204461      Doctorate             16   
32533   54            Private  337992      Bachelors             13   
32534   37            Private  179137   Some-college             10   
32535   22            Private  325033           12th              8   
32536   34            Private  160216      Bachelors             13   
32537   30            Private  345898        HS-grad              9   
32538   38            Private  139180      Bachelors             13   
32539   71                  ?  287372      Doctorate             16   
32540   45          State-gov  252208        HS-grad              9   
32541   41                  ?  202822        HS-grad              9   
32542   72                  ?  129912        HS-grad              9   
32543   45          Local-gov  119199     Assoc-acdm             12   
32544   31            Private  199655        Masters             14   
32545   39          Local-gov  111499     Assoc-acdm             12   
32546   37            Private  198216     Assoc-acdm             12   
32547   43            Private  260761        HS-grad              9   
32548   65   Self-emp-not-inc   99359    Prof-school             15   
32549   43          State-gov  255835   Some-college             10   
32550   43   Self-emp-not-inc   27242   Some-college             10   
32551   32            Private   34066           10th              6   
32552   43            Private   84661      Assoc-voc             11   
32553   32            Private  116138        Masters             14   
32554   53            Private  321865        Masters             14   
32555   22            Private  

# 2 pts Copy all columns with empty values and replace all empty numeric fields with the average of its column in this new column.

==> copied all the numeric feilds to new numeric fields and replaced the zero's with the mode(it takes the most repeated value) of the column.

In [31]:
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
newdf = data.select_dtypes(include=numerics)
column_list = newdf.columns.values
for each_column in column_list:
    data[str(each_column) + '_new'] = newdf[str(each_column)].replace(0,newdf[str(each_column)].mode())
data


age          workclass  fnlwgt      education  education-num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13      32            Private  205019     Assoc-acdm             12   
14      40            Private  121772      Assoc-voc             11   
15      34            Private  245487        7th-8th              4   
16      25   Self-emp-not-inc  176756        HS-grad              9   
17      32            Private  186824        HS-grad              9   
18      38            Private   28887           11th              7   
19      43   Self-emp-not-inc  292175        Masters             14   
20      40            Private  193524      Doctorate             16   
21      54            Private  302146        HS-grad              9   
22      35        Federal-gov   76845            9th              5   
23      43            Private  117037           11th              7   
24      59            Private  109015        HS-grad              9   
25      56          Local-gov  216851      Bachelors             13   
26      19            Private  168294        HS-grad              9   
27      54                  ?  180211   Some-college             10   
28      39            Private  367260        HS-grad              9   
29      49            Private  193366        HS-grad              9   
...    ...                ...     ...            ...            ...   
32531   30                  ?   33811      Bachelors             13   
32532   34            Private  204461      Doctorate             16   
32533   54            Private  337992      Bachelors             13   
32534   37            Private  179137   Some-college             10   
32535   22            Private  325033           12th              8   
32536   34            Private  160216      Bachelors             13   
32537   30            Private  345898        HS-grad              9   
32538   38            Private  139180      Bachelors             13   
32539   71                  ?  287372      Doctorate             16   
32540   45          State-gov  252208        HS-grad              9   
32541   41                  ?  202822        HS-grad              9   
32542   72                  ?  129912        HS-grad              9   
32543   45          Local-gov  119199     Assoc-acdm             12   
32544   31            Private  199655        Masters             14   
32545   39          Local-gov  111499     Assoc-acdm             12   
32546   37            Private  198216     Assoc-acdm             12   
32547   43            Private  260761        HS-grad              9   
32548   65   Self-emp-not-inc   99359    Prof-school             15   
32549   43          State-gov  255835   Some-college             10   
32550   43   Self-emp-not-inc   27242   Some-college             10   
32551   32            Private   34066           10th              6   
32552   43            Private   84661      Assoc-voc             11   
32553   32            Private  116138        Masters             14   
32554   53            Private  321865        Masters             14   
32555   22            Private  

# 2pts Convert non-numeric columns to columns with an integer representations.

==> using FIT TRANSFORM of preprocessing label encoder.
==> And also used used Describe to check the row count and other details.

In [32]:
le = preprocessing.LabelEncoder()
newdf1 = data.select_dtypes(['object'])
for each_non_numeric in newdf1.columns.values:
    data[each_non_numeric] = le.fit_transform(data[each_non_numeric].values)
data

age  workclass  fnlwgt  education  education-num  marital-status  \
0       39          7   77516          9             13               4   
1       50          6   83311          9             13               2   
2       38          4  215646         11              9               0   
3       53          4  234721          1              7               2   
4       28          4  338409          9             13               2   
5       37          4  284582         12             14               2   
6       49          4  160187          6              5               3   
7       52          6  209642         11              9               2   
8       31          4   45781         12             14               4   
9       42          4  159449          9             13               2   
10      37          4  280464         15             10               2   
11      30          7  141297          9             13               2   
12      23          4  122272          9             13               4   
13      32          4  205019          7             12               4   
14      40          4  121772          8             11               2   
15      34          4  245487          5              4               2   
16      25          6  176756         11              9               4   
17      32          4  186824         11              9               4   
18      38          4   28887          1              7               2   
19      43          6  292175         12             14               0   
20      40          4  193524         10             16               2   
21      54          4  302146         11              9               5   
22      35          1   76845          6              5               2   
23      43          4  117037          1              7               2   
24      59          4  109015         11              9               0   
25      56          2  216851          9             13               2   
26      19          4  168294         11              9               4   
27      54          0  180211         15             10               2   
28      39          4  367260         11              9               0   
29      49          4  193366         11              9               2   
...    ...        ...     ...        ...            ...             ...   
32531   30          0   33811          9             13               4   
32532   34          4  204461         10             16               2   
32533   54          4  337992          9             13               2   
32534   37          4  179137         15             10               0   
32535   22          4  325033          2              8               4   
32536   34          4  160216          9             13               4   
32537   30          4  345898         11              9               4   
32538   38          4  139180          9             13               0   
32539   71          0  287372         10             16               2   
32540   45          7  252208         11              9               5   
32541   41          0  202822         11              9               5   
32542   72          0  129912         11              9               2   
32543   45          2  119199          7             12               0   
32544   31          4  199655         12             14               0   
32545   39          2  111499          7             12               2   
32546   37          4  198216          7             12               0   
32547   43          4  260761         11              9               2   
32548   65          6   99359         14             15               4   
32549   43          7  255835         15             10               0   
32550   43          6   27242         15             10               2   
32551   32          4   34066          0              6               2   
32552   43          4   84661   

In [33]:
data.describe()

age     workclass          fnlwgt     education  \
count  32561.000000  32561.000000    32561.000000  32561.000000   
mean      38.581647      3.868892   189778.366512     10.298210   
std       13.640433      1.455960   105549.977697      3.870264   
min       17.000000      0.000000    12285.000000      0.000000   
25%       28.000000      4.000000   117827.000000      9.000000   
50%       37.000000      4.000000   178356.000000     11.000000   
75%       48.000000      4.000000   237051.000000     12.000000   
max       90.000000      8.000000  1484705.000000     15.000000   

       education-num  marital-status    occupation  relationship  \
count   32561.000000    32561.000000  32561.000000  32561.000000   
mean       10.080679        2.611836      6.572740      1.446362   
std         2.572720        1.506222      4.228857      1.606771   
min         1.000000        0.000000      0.000000      0.000000   
25%         9.000000        2.000000      3.000000      0.000000   
50%        10.000000        2.000000      7.000000      1.000000   
75%        12.000000        4.000000     10.000000      3.000000   
max        16.000000        6.000000     14.000000      5.000000   

               race           sex         ...          capital-loss  \
count  32561.000000  32561.000000         ...          32561.000000   
mean       3.665858      0.669205         ...             87.303830   
std        0.848806      0.470506         ...            402.960219   
min        0.000000      0.000000         ...              0.000000   
25%        4.000000      0.000000         ...              0.000000   
50%        4.000000      1.000000         ...              0.000000   
75%        4.000000      1.000000         ...              0.000000   
max        4.000000      1.000000         ...           4356.000000   

       hours-per-week  native-country        Income       age_new  \
count    32561.000000    32561.000000  32561.000000  32561.000000   
mean        40.437456       36.718866      0.240810     38.581647   
std         12.347429        7.823782      0.427581     13.640433   
min          1.000000        0.000000      0.000000     17.000000   
25%         40.000000       39.000000      0.000000     28.000000   
50%         40.000000       39.000000      0.000000     37.000000   
75%         45.000000       39.000000      0.000000     48.000000   
max         99.000000       41.000000      1.000000     90.000000   

           fnlwgt_new  education-num_new  capital-gain_new  capital-loss_new  \
count    32561.000000       32561.000000      32561.000000      32561.000000   
mean    189778.366512          10.080679       1077.648844         87.303830   
std     105549.977697           2.572720       7385.292085        402.960219   
min      12285.000000           1.000000          0.000000          0.000000   
25%     117827.000000           9.000000          0.000000          0.000000   
50%     178356.000000          10.000000          0.000000          0.000000   
75%     237051.000000          12.000000          0.000000          0.000000   
max    1484705.000000          16.000000      99999.000000       4356.000000   

       hours-per-week_new  
count        32561.000000  
mean            40.437456  
std             12.347429  
min              1.000000  
25%             40.000000  
50%             40.000000  
75%             45.000000  
max             99.000000  

[8 rows x 21 columns]

# 2 pts Convert the data to a numpy array

==> using Numpy converted the data into array's.

==> training data contains all the array of the given datasets which exclude's INCOME column(Vector result)

In [34]:

training_data = np.array(data)
training_data = training_data[:,[3,5,6,7,8,9,13,15,16,17,18,19,20]]
training_data


array([[    9,     4,     1, ...,  2174,     0,    40],
       [    9,     2,     4, ...,     0,     0,    13],
       [   11,     0,     6, ...,     0,     0,    40],
       ..., 
       [   11,     6,     1, ...,     0,     0,    40],
       [   11,     4,     1, ...,     0,     0,    20],
       [   11,     2,     4, ..., 15024,     0,    40]], dtype=int64)

==> In training Result I am storing the INCOME(vector result)

In [35]:
training_result = np.array(data)
training_result = training_result[:,[14]]
training_result

array([[0],
       [0],
       [0],
       ..., 
       [0],
       [0],
       [1]], dtype=int64)

# 2 pts Divide the data into a training and test set.

==>here we are splitting the data into training and test set.

In [36]:
from sklearn.cross_validation import train_test_split
training_data1, test_data, training_result1, test_result = train_test_split(training_data, training_result, test_size=0.33, random_state=0)
training_data1

array([[  15,    4,    1, ...,    0,    0,   15],
       [  11,    4,    5, ..., 8614,    0,   40],
       [   6,    0,    7, ...,    0,    0,   40],
       ..., 
       [  15,    5,   12, ...,    0,    0,   40],
       [  10,    2,    4, ..., 7688,    0,   45],
       [  15,    4,    8, ..., 2597,    0,   48]], dtype=int64)

In [37]:
training_result1

array([[0],
       [1],
       [0],
       ..., 
       [0],
       [1],
       [0]], dtype=int64)

# 2 pts Run a random forest on the training set.

==> here Random forest has been trainned with training data and training result using FIT method

In [38]:
model = RandomForestClassifier(n_estimators=100 , oob_score = True , random_state = 42)
model.fit(training_data1,training_result1.ravel())

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=True, random_state=42, verbose=0, warm_start=False)

# 2 pts Compute the accuracy of predictions on the test set.

==> here we are using the model which we have created with training data and we are using the test data  to predict the vector result.

==>since, we have generated the output which was predicted by Random Forest we need to compare the generated output with test _ result for accuracy score(this is done using metrics accuracy). 

In [39]:
output = model.predict(test_data)
output

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [40]:
metrics.accuracy_score(output,test_result)

0.85231714126186486

# classification Report on Income(> 50 and < 50).

In [41]:
from sklearn.metrics import classification_report
target_names = ['<50','>50']
classification_report(test_result,output,target_names=target_names)


'             precision    recall  f1-score   support\n\n        <50       0.88      0.93      0.90      8151\n        >50       0.73      0.62      0.67      2595\n\navg / total       0.85      0.85      0.85     10746\n'